function outputs = make_cvf_ae_closed_loop_framework(figureDir)
%MAKE_CVF_AE_CLOSED_LOOP_FRAMEWORK Draw the paper-level CVF-AE framework.
%
% The schematic contains only the F/P/R paper mechanism and does not run
% an optimizer or expose optional implementation branches.

projectRoot = fileparts(mfilename('fullpath'));
if nargin < 1 || isempty(figureDir)
    figureDir = fullfile(projectRoot, 'routes', 'route_b_cvf_ae', ...
        'paper_ajse_zh', 'figures');
end
assert(isfolder(figureDir), 'Missing paper figure directory: %s', figureDir);

colors = struct();
colors.ink = [0.12, 0.14, 0.16];
colors.guide = [0.48, 0.53, 0.56];
colors.greenFill = [0.86, 0.93, 0.89];
colors.greenEdge = [0.20, 0.50, 0.36];
colors.blueFill = [0.88, 0.93, 0.97];
colors.blueEdge = [0.12, 0.38, 0.60];
colors.goldFill = [0.97, 0.93, 0.80];
colors.goldEdge = [0.62, 0.45, 0.12];
colors.purpleFill = [0.92, 0.89, 0.97];
colors.purpleEdge = [0.40, 0.25, 0.65];
colors.orangeFill = [0.97, 0.89, 0.82];
colors.orangeEdge = [0.72, 0.30, 0.08];
colors.grayFill = [0.94, 0.94, 0.94];
colors.grayEdge = [0.35, 0.37, 0.39];

fig = figure( ...
    'Visible', 'off', ...
    'Color', 'w', ...
    'Position', [80, 60, 560, 700]);
ax = axes(fig, 'Position', [0.025, 0.015, 0.95, 0.97]);
hold(ax, 'on');
axis(ax, 'off');
xlim(ax, [0, 10]);
ylim(ax, [0, 13]);

localBlock(ax, [2.0, 11.85, 6.0, 0.72], ...
    colors.greenFill, colors.greenEdge, ...
    'Map, start/goal, and fixed settings', '', 11.0, 9.0);

localArrow(ax, [5.0, 11.84], [5.0, 11.30], colors.guide);
localBlock(ax, [1.05, 10.05, 7.90, 1.20], ...
    colors.blueFill, colors.blueEdge, ...
    'Constraint-aware initialization', ...
    'Reference path and guided population', 12.2, 9.8);
localTag(ax, 0.52, 10.65, '1', colors.blueEdge);
text(ax, 0.12, 10.05, 'Where to start', ...
    'Rotation', 90, ...
    'HorizontalAlignment', 'center', ...
    'FontName', 'Times New Roman', ...
    'FontSize', 9.2, ...
    'Color', colors.blueEdge);

localArrow(ax, [5.0, 10.04], [5.0, 9.43], colors.guide);
localBlock(ax, [1.05, 8.08, 7.90, 1.28], ...
    colors.goldFill, colors.goldEdge, ...
    'F/P/R state scheduling', ...
    'Population observations  \rightarrow  requested q_t  \rightarrow  active s_t', ...
    12.2, 9.6);
localTag(ax, 0.52, 8.72, '2', colors.goldEdge);
text(ax, 0.12, 8.08, 'When to intervene', ...
    'Rotation', 90, ...
    'HorizontalAlignment', 'center', ...
    'FontName', 'Times New Roman', ...
    'FontSize', 9.2, ...
    'Color', colors.goldEdge);

localArrow(ax, [5.0, 8.07], [5.0, 7.43], colors.guide);
localBlock(ax, [1.05, 5.93, 7.90, 1.42], ...
    colors.purpleFill, colors.purpleEdge, ...
    'Sparse CVF candidate generation', ...
    'AE direction + CVF pressure + quality direction', 12.2, 9.8);
localTag(ax, 0.52, 6.64, '3', colors.purpleEdge);
text(ax, 0.12, 5.93, 'How to move', ...
    'Rotation', 90, ...
    'HorizontalAlignment', 'center', ...
    'FontName', 'Times New Roman', ...
    'FontSize', 9.2, ...
    'Color', colors.purpleEdge);

localArrow(ax, [5.0, 5.92], [5.0, 5.28], colors.guide);
localBlock(ax, [1.05, 3.78, 7.90, 1.42], ...
    colors.orangeFill, colors.orangeEdge, ...
    'Conservative acceptance and sparse repair', ...
    'Local gate  \rightarrow  Deb population update', 12.0, 9.8);
localTag(ax, 0.52, 4.49, '4', colors.orangeEdge);
text(ax, 0.12, 3.78, 'What to retain', ...
    'Rotation', 90, ...
    'HorizontalAlignment', 'center', ...
    'FontName', 'Times New Roman', ...
    'FontSize', 9.2, ...
    'Color', colors.orangeEdge);

localArrow(ax, [5.0, 3.77], [5.0, 3.16], colors.guide);
localBlock(ax, [2.0, 2.25, 6.0, 0.84], ...
    colors.grayFill, colors.grayEdge, ...
    'Updated population and current best', '', 11.0, 9.0);

plot(ax, [8.0, 9.55, 9.55, 8.95], ...
    [2.67, 2.67, 8.72, 8.72], ...
    '-', ...
    'Color', colors.guide, ...
    'LineWidth', 1.25);
quiver(ax, 8.95, 8.72, -0.52, 0, 0, ...
    'Color', colors.guide, ...
    'LineWidth', 1.25, ...
    'MaxHeadSize', 0.9);
text(ax, 9.78, 5.66, ...
    {'Population feedback', ...
    'feasibility, violation, diversity, progress'}, ...
    'Rotation', 90, ...
    'HorizontalAlignment', 'center', ...
    'VerticalAlignment', 'middle', ...
    'FontName', 'Times New Roman', ...
    'FontSize', 8.8, ...
    'Color', colors.guide, ...
    'Interpreter', 'tex');

localArrow(ax, [5.0, 2.24], [5.0, 1.62], colors.guide);
localBlock(ax, [2.0, 0.68, 6.0, 0.86], ...
    colors.greenFill, colors.greenEdge, ...
    'Best feasible path after termination', '', 11.0, 9.0);

baseName = "cvf_ae_closed_loop_framework";
pngPath = fullfile(figureDir, baseName + ".png");
pdfPath = fullfile(figureDir, baseName + ".pdf");
exportgraphics(fig, pngPath, ...
    'Resolution', 300, ...
    'BackgroundColor', 'white');
exportgraphics(fig, pdfPath, ...
    'ContentType', 'vector', ...
    'BackgroundColor', 'white');
close(fig);

outputs = struct('pngPath', pngPath, 'pdfPath', pdfPath);
fprintf('CVF-AE framework figure written to:\n%s\n%s\n', pngPath, pdfPath);
end

function localBlock(ax, position, faceColor, edgeColor, ...
        titleText, subtitleText, titleSize, subtitleSize)
rectangle(ax, ...
    'Position', position, ...
    'Curvature', 0.05, ...
    'FaceColor', faceColor, ...
    'EdgeColor', edgeColor, ...
    'LineWidth', 1.25);
centerX = position(1) + position(3) / 2;
centerY = position(2) + position(4) / 2;
if strlength(subtitleText) == 0
    text(ax, centerX, centerY, titleText, ...
        'HorizontalAlignment', 'center', ...
        'VerticalAlignment', 'middle', ...
        'FontName', 'Times New Roman', ...
        'FontSize', titleSize, ...
        'Color', [0.12, 0.14, 0.16]);
else
    text(ax, centerX, centerY + 0.20, titleText, ...
        'HorizontalAlignment', 'center', ...
        'VerticalAlignment', 'middle', ...
        'FontName', 'Times New Roman', ...
        'FontSize', titleSize, ...
        'FontWeight', 'bold', ...
        'Color', [0.12, 0.14, 0.16]);
    text(ax, centerX, centerY - 0.24, subtitleText, ...
        'HorizontalAlignment', 'center', ...
        'VerticalAlignment', 'middle', ...
        'FontName', 'Times New Roman', ...
        'FontSize', subtitleSize, ...
        'Color', [0.28, 0.31, 0.33], ...
        'Interpreter', 'tex');
end
end

function localArrow(ax, startPoint, endPoint, color)
delta = endPoint - startPoint;
quiver(ax, startPoint(1), startPoint(2), delta(1), delta(2), 0, ...
    'Color', color, ...
    'LineWidth', 1.15, ...
    'MaxHeadSize', 0.85);
end

function localTag(ax, x, y, label, color)
scatter(ax, x, y, 255, color, ...
    'filled', ...
    'MarkerEdgeColor', 'w', ...
    'LineWidth', 0.8);
text(ax, x, y, label, ...
    'HorizontalAlignment', 'center', ...
    'VerticalAlignment', 'middle', ...
    'FontName', 'Times New Roman', ...
    'FontSize', 10.0, ...
    'FontWeight', 'bold', ...
    'Color', 'w');
end
