function outputs = make_cvf_ae_ablation_summary_figure(sourceDir, figureDir)
%MAKE_CVF_AE_ABLATION_SUMMARY_FIGURE Plot compact ablation summaries.
%
% The function reads the archived formal ablation table and creates a
% scene-rank heatmap and feasibility-rate line plot. It does not rerun any
% optimizer or alter the frozen result records.

projectRoot = fileparts(mfilename('fullpath'));
if nargin < 1 || isempty(sourceDir)
    sourceDir = fullfile(projectRoot, 'routes', 'route_b_cvf_ae', 'results', ...
        'cvf_ae_corrected_ablation_paper_artifacts_20260730');
end
if nargin < 2 || isempty(figureDir)
    figureDir = fullfile(projectRoot, 'routes', 'route_b_cvf_ae', ...
        'paper_ajse_zh', 'figures');
end

sourcePath = fullfile(sourceDir, 'paper_table_ablation.csv');
assert(isfile(sourcePath), 'Missing formal ablation table: %s', sourcePath);
assert(isfolder(figureDir), 'Missing paper figure directory: %s', figureDir);

variantNames = [
    "CVF-AE"
    "CVF-AE-w/o-CVF"
    "CVF-AE-w/o-StateAdaptiveCVF"
    "CVF-AE-w/o-SparsePreservation"
    "CVF-AE-w/o-Init"
    "Base-AE"];
variantLabels = ["V0", "V1", "V2", "V3", "V4", "V5"];
sceneIds = 1:3;
ablation = readtable(sourcePath, 'TextType', 'string');

sceneRanks = nan(numel(variantNames), numel(sceneIds));
feasibility = nan(numel(variantNames), numel(sceneIds));
for variantIndex = 1:numel(variantNames)
    for sceneIndex = 1:numel(sceneIds)
        mask = ablation.Variant == variantNames(variantIndex) & ...
            ablation.Scene == sceneIds(sceneIndex);
        assert(nnz(mask) == 1, ...
            'Expected one row for %s in Scene %d.', ...
            variantNames(variantIndex), sceneIds(sceneIndex));
        sceneRanks(variantIndex, sceneIndex) = ablation.SceneRank(mask);
        feasibility(variantIndex, sceneIndex) = ablation.FeasibleRate(mask);
    end
end

rankBaseName = "ablation_scene_rank_heatmap";
feasibilityBaseName = "ablation_feasibility_rates";
commonAxesPosition = [0.10, 0.14, 0.88, 0.74];
rankAxesPosition = [0.10, 0.14, 0.78, 0.74];
rankColorbarPosition = [0.91, 0.14, 0.025, 0.74];

rankFigure = figure( ...
    'Visible', 'off', ...
    'Color', 'w', ...
    'Position', [80, 80, 650, 560]);
rankAxes = axes(rankFigure);
set(rankAxes, 'Position', rankAxesPosition);
imagesc(rankAxes, sceneIds, 1:numel(variantLabels), sceneRanks);
rankColors = [
    0.00, 0.14, 0.32
    0.08, 0.32, 0.50
    0.22, 0.49, 0.64
    0.43, 0.65, 0.73
    0.67, 0.78, 0.80
    0.88, 0.90, 0.89];
colormap(rankAxes, rankColors);
clim(rankAxes, [0.5, 6.5]);
set(rankAxes, ...
    'XTick', sceneIds, ...
    'XTickLabel', compose('Scene %d', sceneIds), ...
    'YTick', 1:numel(variantLabels), ...
    'YTickLabel', variantLabels, ...
    'FontName', 'Times New Roman', ...
    'FontSize', 11, ...
    'LineWidth', 0.9, ...
    'TickLength', [0, 0], ...
    'Box', 'on');
xlabel(rankAxes, 'Test scene');
ylabel(rankAxes, 'Ablation variant');
rankColorbar = colorbar(rankAxes, 'eastoutside');
set(rankColorbar, ...
    'Position', rankColorbarPosition, ...
    'Ticks', 1:6, ...
    'FontName', 'Times New Roman', ...
    'FontSize', 10, ...
    'LineWidth', 0.8);
rankColorbar.Label.String = 'Rank';
rankColorbar.Label.FontName = 'Times New Roman';
rankColorbar.Label.FontSize = 10;
hold(rankAxes, 'on');
for variantIndex = 1:numel(variantLabels)
    for sceneIndex = 1:numel(sceneIds)
        textColor = [0.10, 0.10, 0.10];
        if sceneRanks(variantIndex, sceneIndex) <= 3
            textColor = [1.00, 1.00, 1.00];
        end
        text(rankAxes, sceneIndex, variantIndex, ...
            sprintf('%d', sceneRanks(variantIndex, sceneIndex)), ...
            'Color', textColor, ...
            'FontName', 'Times New Roman', ...
            'FontSize', 11, ...
            'FontWeight', 'bold', ...
            'HorizontalAlignment', 'center', ...
            'VerticalAlignment', 'middle');
    end
end
set(rankAxes, 'Position', rankAxesPosition);
set(rankColorbar, 'Position', rankColorbarPosition);
localExport(rankFigure, sourceDir, figureDir, rankBaseName);
close(rankFigure);

feasibilityFigure = figure( ...
    'Visible', 'off', ...
    'Color', 'w', ...
    'Position', [80, 80, 650, 560]);
feasibilityAxes = axes(feasibilityFigure);
set(feasibilityAxes, 'Position', commonAxesPosition);
hold(feasibilityAxes, 'on');
sceneColors = [
    0.00, 0.45, 0.70
    0.84, 0.37, 0.00
    0.40, 0.25, 0.65];
sceneMarkers = {'o', 's', '^'};
lineHandles = gobjects(numel(sceneIds), 1);
variantPositions = 1:numel(variantLabels);
sceneOffsets = [-0.10, 0, 0.10];
for sceneIndex = 1:numel(sceneIds)
    lineHandles(sceneIndex) = plot(feasibilityAxes, ...
        variantPositions + sceneOffsets(sceneIndex), ...
        feasibility(:, sceneIndex), ...
        'Color', sceneColors(sceneIndex, :), ...
        'LineStyle', 'none', ...
        'LineWidth', 1.2, ...
        'Marker', sceneMarkers{sceneIndex}, ...
        'MarkerSize', 7.0, ...
        'MarkerFaceColor', 'w', ...
        'MarkerEdgeColor', sceneColors(sceneIndex, :));
end
set(feasibilityAxes, ...
    'XTick', variantPositions, ...
    'XTickLabel', variantLabels, ...
    'YTick', 0:0.2:1, ...
    'FontName', 'Times New Roman', ...
    'FontSize', 11, ...
    'LineWidth', 0.9, ...
    'Box', 'on', ...
    'YGrid', 'on', ...
    'XGrid', 'off', ...
    'GridAlpha', 0.16);
xlim(feasibilityAxes, [0.7, numel(variantLabels) + 0.3]);
ylim(feasibilityAxes, [0, 1.05]);
xlabel(feasibilityAxes, 'Ablation variant');
ylabel(feasibilityAxes, 'Feasibility rate');
legend(feasibilityAxes, lineHandles, compose('Scene %d', sceneIds), ...
    'Location', 'northoutside', ...
    'Orientation', 'horizontal', ...
    'NumColumns', 3, ...
    'Box', 'off', ...
    'FontName', 'Times New Roman', ...
    'FontSize', 9.5);
set(feasibilityAxes, 'Position', commonAxesPosition);
localExport(feasibilityFigure, sourceDir, figureDir, feasibilityBaseName);
close(feasibilityFigure);

outputs = struct();
outputs.sourceDir = sourceDir;
outputs.rankPng = fullfile(figureDir, rankBaseName + ".png");
outputs.feasibilityPng = fullfile(figureDir, feasibilityBaseName + ".png");
fprintf('Ablation summary figures written to:\n%s\n%s\n', ...
    outputs.rankPng, outputs.feasibilityPng);
end

function localExport(fig, sourceDir, figureDir, baseName)
resultPng = fullfile(sourceDir, baseName + ".png");
resultPdf = fullfile(sourceDir, baseName + ".pdf");
paperPng = fullfile(figureDir, baseName + ".png");
set(fig, 'PaperPositionMode', 'auto', 'InvertHardcopy', 'off');
print(fig, char(resultPng), '-dpng', '-r300');
exportgraphics(fig, resultPdf, 'ContentType', 'vector', 'BackgroundColor', 'white');
copyfile(resultPng, paperPng);
end
