function outputs = make_cvf_ae_significance_heatmap(figureDir)
%MAKE_CVF_AE_SIGNIFICANCE_HEATMAP Draw the active effect-size heatmap.
%
% The heatmap reads the frozen selected-seven Holm and Cliff's delta table.

projectRoot = fileparts(mfilename('fullpath'));
if nargin < 1 || isempty(figureDir)
    figureDir = fullfile(projectRoot, 'routes', 'route_b_cvf_ae', ...
        'paper_ajse_zh', 'figures');
end
assert(isfolder(figureDir), 'Missing paper figure directory: %s', figureDir);

sourcePath = fullfile(projectRoot, 'routes', 'route_b_cvf_ae', ...
    'results', 'cvf_ae_selected7_paper_artifacts_rerun_20260707_101155', ...
    'selected7_pairwise_rank_sum_holm.csv');
assert(isfile(sourcePath), 'Missing significance table: %s', sourcePath);
pairwise = readtable(sourcePath, 'TextType', 'string');

baselines = ["AE", "PSO", "GWO", "HHO", "ERIME", "MSCSO"];
sceneIds = 1:3;
effect = nan(numel(sceneIds), numel(baselines));
relation = strings(size(effect));
for sceneIndex = 1:numel(sceneIds)
    for baselineIndex = 1:numel(baselines)
        mask = pairwise.Scene == sceneIds(sceneIndex) & ...
            pairwise.Baseline == baselines(baselineIndex);
        assert(nnz(mask) == 1, ...
            'Expected one significance row for Scene %d, %s.', ...
            sceneIds(sceneIndex), baselines(baselineIndex));
        effect(sceneIndex, baselineIndex) = ...
            pairwise.CliffsDeltaLowerBetter(mask);
        relation(sceneIndex, baselineIndex) = ...
            pairwise.SceneHolmResult(mask);
    end
end

fig = figure( ...
    'Visible', 'off', ...
    'Color', 'w', ...
    'Position', [80, 80, 1060, 500]);
ax = axes(fig, 'Position', [0.10, 0.18, 0.76, 0.72]);
imagesc(ax, 1:numel(baselines), sceneIds, effect);
colormap(ax, localDivergingPalette(121));
clim(ax, [-1, 1]);
set(ax, ...
    'XTick', 1:numel(baselines), ...
    'XTickLabel', baselines, ...
    'YTick', sceneIds, ...
    'YTickLabel', compose('Scene %d', sceneIds), ...
    'FontName', 'Times New Roman', ...
    'FontSize', 11, ...
    'LineWidth', 0.9, ...
    'TickLength', [0, 0], ...
    'Box', 'on');
xlabel(ax, 'Baseline');
ylabel(ax, 'Test scene');

for sceneIndex = 1:numel(sceneIds)
    for baselineIndex = 1:numel(baselines)
        textColor = [0.12, 0.12, 0.12];
        if abs(effect(sceneIndex, baselineIndex)) > 0.62
            textColor = [1, 1, 1];
        end
        text(ax, baselineIndex, sceneIndex, ...
            sprintf('%+.2f  %s', ...
            effect(sceneIndex, baselineIndex), ...
            relation(sceneIndex, baselineIndex)), ...
            'HorizontalAlignment', 'center', ...
            'VerticalAlignment', 'middle', ...
            'FontName', 'Times New Roman', ...
            'FontSize', 10, ...
            'FontWeight', 'bold', ...
            'Color', textColor);
    end
end

colorBar = colorbar(ax, 'eastoutside');
colorBar.Position = [0.89, 0.18, 0.025, 0.72];
colorBar.Label.String = 'Cliff''s delta';
colorBar.Label.FontName = 'Times New Roman';
colorBar.FontName = 'Times New Roman';

baseName = "selected7_effect_size_heatmap";
pngPath = fullfile(figureDir, baseName + ".png");
pdfPath = fullfile(figureDir, baseName + ".pdf");
exportgraphics(fig, pngPath, ...
    'Resolution', 300, ...
    'BackgroundColor', 'white');
exportgraphics(fig, pdfPath, ...
    'ContentType', 'vector', ...
    'BackgroundColor', 'white');
close(fig);

outputs = struct('pngPath', pngPath, 'pdfPath', pdfPath);
fprintf('Significance heatmap written to:\n%s\n%s\n', pngPath, pdfPath);
end

function colors = localDivergingPalette(count)
anchors = [
    0.82, 0.39, 0.16
    0.96, 0.96, 0.94
    0.08, 0.36, 0.58];
x = linspace(0, 1, size(anchors, 1));
xi = linspace(0, 1, count);
colors = interp1(x, anchors, xi, 'linear');
end
