function out = make_cvf_ae_corrected_ablation_artifacts(sourceDir, outDir)
%MAKE_CVF_AE_CORRECTED_ABLATION_ARTIFACTS Rebuild corrected paper artifacts.
%
% This function reads completed formal-ablation records. It does not run
% any optimizer and does not write the manuscript's LaTeX tables.

projectRoot = fileparts(mfilename('fullpath'));
resultsRoot = fullfile(projectRoot, 'routes', 'route_b_cvf_ae', 'results');
if nargin < 1 || isempty(sourceDir)
    sourceDir = fullfile(resultsRoot, ...
        'cvf_ae_formal_ablation_corrected_20260730_v2');
end
if nargin < 2 || isempty(outDir)
    outDir = fullfile(resultsRoot, ...
        'cvf_ae_corrected_ablation_paper_artifacts_20260730');
end
if ~exist(outDir, 'dir')
    mkdir(outDir);
end

runDir = fullfile(sourceDir, 'run_records');
runFiles = dir(fullfile(runDir, 'scene*_run*.mat'));
assert(numel(runFiles) == 540, ...
    'Expected 540 formal-ablation records, found %d.', numel(runFiles));

summary = readtable(fullfile(sourceDir, 'cvf_ae_gate_summary.csv'), ...
    'TextType', 'string');
averageRank = readtable(fullfile(sourceDir, ...
    'cvf_ae_gate_average_rank.csv'), 'TextType', 'string');

variantOrder = ["CVF-AE"; "CVF-AE-w/o-CVF"; ...
    "CVF-AE-w/o-StateAdaptiveCVF"; ...
    "CVF-AE-w/o-SparsePreservation"; ...
    "CVF-AE-w/o-Init"; "Base-AE"];
assert(height(summary) == 18, 'Expected 18 aggregate ablation rows.');
assert(all(ismember(variantOrder, summary.Algorithm)), ...
    'Corrected summary is missing an ablation variant.');

paperTable = localBuildPaperTable(summary, averageRank, variantOrder);
writetable(paperTable, fullfile(outDir, 'paper_table_ablation.csv'));

overhead = localBuildOverhead(summary);
writetable(overhead, fullfile(outDir, 'corrected_ablation_overhead.csv'));

paperDir = fullfile(projectRoot, 'routes', 'route_b_cvf_ae', ...
    'paper_ajse_zh');
figureDir = fullfile(paperDir, 'figures');
make_cvf_ae_ablation_summary_figure(outDir, figureDir);

analyze_cvf_ae_trajectory_sanity(sourceDir);
mainDir = fullfile(resultsRoot, ...
    'cvf_ae_main_comparison_formal_conservative_20260623_091132');
recentDir = fullfile(resultsRoot, ...
    'cvf_ae_main_comparison_recent_improved_formal_20260623_161229');
representativeDir = fullfile(outDir, 'representative_paths');
make_cvf_ae_representative_path_figures( ...
    mainDir, recentDir, sourceDir, representativeDir);
representativeSource = fullfile(representativeDir, 'ablation', ...
    'ablation_scene3_representative_3d.png');
representativeTarget = fullfile(figureDir, ...
    'ablation_scene3_representative_3d.png');
assert(isfile(representativeSource), ...
    'Missing corrected representative path: %s', representativeSource);
copyfile(representativeSource, representativeTarget);

out = struct();
out.sourceDir = sourceDir;
out.outDir = outDir;
out.paperTable = paperTable;
out.overhead = overhead;
out.representativeFigure = representativeTarget;

fprintf('\nCorrected ablation paper artifacts written to:\n%s\n', outDir);
end

function paperTable = localBuildPaperTable(summary, averageRank, variantOrder)
paperTable = table();
for idx = 1:numel(variantOrder)
    variant = variantOrder(idx);
    rows = summary(summary.Algorithm == variant, :);
    assert(height(rows) == 3, ...
        'Expected three scene rows for %s.', variant);
    rankRow = averageRank(averageRank.Algorithm == variant, :);
    assert(height(rankRow) == 1, ...
        'Expected one average-rank row for %s.', variant);

    block = table( ...
        cvfAePaperSceneId(rows.Scene), ...
        rows.Algorithm, ...
        rows.MeanBestFitness, ...
        rows.StdBestFitness, ...
        rows.FeasibleRate, ...
        rows.Rank, ...
        repmat(rankRow.AverageRank, 3, 1), ...
        rows.MeanRuntime, ...
        rows.MeanNEvals, ...
        rows.MeanFirstFeasibleIter, ...
        rows.MeanRepairCount, ...
        rows.MeanViabilityFieldCount, ...
        rows.MeanViabilityFieldSuccessCount, ...
        'VariableNames', {'Scene', 'Variant', 'MeanFitness', ...
        'StdFitness', 'FeasibleRate', 'SceneRank', 'AverageRank', ...
        'RuntimeSeconds', 'NEvals', 'FirstFeasibleIteration', ...
        'RepairCount', 'CVFTriggerCount', 'CVFSuccessCount'});
    paperTable = [paperTable; block]; %#ok<AGROW>
end
paperTable.VariantOrder = localOrder(paperTable.Variant, variantOrder);
paperTable = sortrows(paperTable, {'Scene', 'VariantOrder'});
paperTable.VariantOrder = [];
end

function overhead = localBuildOverhead(summary)
overhead = table();
for sceneId = [1, 2, 4]
    rows = summary(summary.Scene == sceneId, :);
    withoutCvf = rows(rows.Algorithm == "CVF-AE-w/o-CVF", :);
    assert(height(withoutCvf) == 1, ...
        'Missing w/o-CVF row for internal Scene %d.', sceneId);
    block = table( ...
        cvfAePaperSceneId(rows.Scene), rows.Algorithm, ...
        rows.MeanNEvals, rows.MeanViabilityFieldCount, ...
        rows.MeanViabilityFieldSuccessCount, ...
        rows.MeanNEvals ./ withoutCvf.MeanNEvals, ...
        'VariableNames', {'Scene', 'Variant', 'NEvals', ...
        'CVFTriggerCount', 'CVFSuccessCount', ...
        'NEvalsRatioVsWithoutCVF'});
    overhead = [overhead; block]; %#ok<AGROW>
end
end

function order = localOrder(values, desiredOrder)
values = string(values);
order = nan(numel(values), 1);
for idx = 1:numel(desiredOrder)
    order(values == desiredOrder(idx)) = idx;
end
assert(all(isfinite(order)), 'Unexpected ablation variant.');
end
