function outputs = make_cvf_pressure_mapping_figure(figureDir)
%MAKE_CVF_PRESSURE_MAPPING_FIGURE Draw the paper CVF mapping schematic.
%
% The schematic uses the paper palette and does not evaluate an optimizer.

projectRoot = fileparts(mfilename('fullpath'));
if nargin < 1 || isempty(figureDir)
    figureDir = fullfile(projectRoot, 'routes', 'route_b_cvf_ae', ...
        'paper_ajse_zh', 'figures');
end
assert(isfolder(figureDir), 'Missing paper figure directory: %s', figureDir);

baseName = "cvf_pressure_mapping_and_synthesis";
pngPath = fullfile(figureDir, baseName + ".png");
pdfPath = fullfile(figureDir, baseName + ".pdf");

colors = struct();
colors.path = [0.00, 0.14, 0.32];
colors.sample = [0.84, 0.37, 0.00];
colors.control = [0.02, 0.42, 0.47];
colors.obstacle = [0.72, 0.76, 0.78];
colors.guide = [0.55, 0.61, 0.65];
pressureColors = [
    0.68, 0.20, 0.18
    0.65, 0.30, 0.40
    0.40, 0.25, 0.65];

fig = figure( ...
    'Visible', 'off', ...
    'Color', 'w', ...
    'Position', [80, 80, 540, 452]);
ax = axes(fig, 'Position', [0.035, 0.035, 0.93, 0.93]);
hold(ax, 'on');
axis(ax, 'off');
xlim(ax, [0, 8]);
ylim(ax, [0, 7.2]);

text(ax, 4.0, 6.92, 'Global view: sample-to-control mapping', ...
    'HorizontalAlignment', 'center', ...
    'FontName', 'Times New Roman', ...
    'FontSize', 12);

rectangle(ax, 'Position', [0.45, 4.70, 1.75, 1.25], ...
    'FaceColor', colors.obstacle, ...
    'EdgeColor', colors.guide * 0.75, ...
    'LineWidth', 0.9);
text(ax, 1.33, 5.32, 'Obstacle', ...
    'HorizontalAlignment', 'center', ...
    'FontName', 'Times New Roman', ...
    'FontSize', 9.5, ...
    'Color', [0.32, 0.36, 0.38]);

theta = linspace(0, 2*pi, 240);
nfzCenter = [5.85, 4.05];
nfzRadius = 0.70;
plot(ax, nfzCenter(1) + nfzRadius*cos(theta), ...
    nfzCenter(2) + nfzRadius*sin(theta), ...
    'Color', pressureColors(2, :), ...
    'LineWidth', 1.1);
text(ax, nfzCenter(1), nfzCenter(2), 'NFZ', ...
    'HorizontalAlignment', 'center', ...
    'FontName', 'Times New Roman', ...
    'FontSize', 9.5, ...
    'Color', pressureColors(2, :));

pathX = linspace(0.20, 7.65, 260);
knotsX = [0.20, 1.35, 2.55, 3.75, 5.10, 6.20, 7.65];
knotsY = [3.45, 3.78, 4.10, 4.50, 5.02, 5.62, 6.25];
pathY = pchip(knotsX, knotsY, pathX);
plot(ax, pathX, pathY, ...
    'Color', colors.path, ...
    'LineWidth', 2.3);

sampleX = [2.55, 3.70, 4.80];
sampleY = pchip(knotsX, knotsY, sampleX);
controlPoint = [6.20, pchip(knotsX, knotsY, 6.20)];
scatter(ax, controlPoint(1), controlPoint(2), 74, colors.path, ...
    'filled', ...
    'MarkerEdgeColor', 'w', ...
    'LineWidth', 0.75);

for sampleIndex = 1:numel(sampleX)
    plot(ax, [sampleX(sampleIndex), controlPoint(1)], ...
        [sampleY(sampleIndex), controlPoint(2)], ...
        ':', ...
        'Color', colors.guide, ...
        'LineWidth', 0.75);
end

pressureVectors = [
    -0.80, 0.42
    -0.45, 0.72
     0.05, 0.50];
for sampleIndex = 1:numel(sampleX)
    scatter(ax, sampleX(sampleIndex), sampleY(sampleIndex), ...
        48, pressureColors(sampleIndex, :), ...
        'filled', ...
        'MarkerEdgeColor', 'w', ...
        'LineWidth', 0.65);
    quiver(ax, sampleX(sampleIndex), sampleY(sampleIndex), ...
        pressureVectors(sampleIndex, 1), pressureVectors(sampleIndex, 2), ...
        0, ...
        'Color', pressureColors(sampleIndex, :), ...
        'LineWidth', 1.35, ...
        'MaxHeadSize', 0.72);
    text(ax, sampleX(sampleIndex) - 0.10, sampleY(sampleIndex) - 0.30, ...
        sprintf('F(p_%d)', sampleIndex), ...
        'HorizontalAlignment', 'center', ...
        'FontName', 'Times New Roman', ...
        'FontSize', 10.0, ...
        'Color', pressureColors(sampleIndex, :));
end

mappedIncrement = mean(pressureVectors, 1);
quiver(ax, controlPoint(1), controlPoint(2), ...
    mappedIncrement(1), mappedIncrement(2), ...
    0, ...
    'Color', colors.control, ...
    'LineWidth', 2.25, ...
    'MaxHeadSize', 0.70);

text(ax, controlPoint(1) + 0.18, controlPoint(2) + 0.18, ...
    'Control point q_k', ...
    'FontName', 'Times New Roman', ...
    'FontSize', 10.0, ...
    'Color', colors.path);
text(ax, 5.02, 6.18, 'Mean mapped pressure', ...
    'FontName', 'Times New Roman', ...
    'FontSize', 10.0, ...
    'Color', colors.control);

plot(ax, [0.20, 7.80], [3.35, 3.35], ...
    '-', ...
    'Color', [0.84, 0.86, 0.87], ...
    'LineWidth', 0.9);
quiver(ax, 4.0, 3.55, 0, -0.42, 0, ...
    'Color', colors.guide * 0.82, ...
    'LineWidth', 1.0, ...
    'MaxHeadSize', 0.9);

text(ax, 4.0, 3.02, 'Local view at q_k: same pressures and their mean', ...
    'HorizontalAlignment', 'center', ...
    'FontName', 'Times New Roman', ...
    'FontSize', 12);

origin = [4.45, 0.72];
displayScale = 2.25;
labelOffsets = [
    -0.22, 0.10
     0.18, 0.14
     0.14, 0.08];
for sampleIndex = 1:size(pressureVectors, 1)
    vector = displayScale * pressureVectors(sampleIndex, :);
    quiver(ax, origin(1), origin(2), ...
        vector(1), vector(2), ...
        0, ...
        'Color', pressureColors(sampleIndex, :), ...
        'LineWidth', 1.35, ...
        'MaxHeadSize', 0.68);
    labelPoint = origin + vector + labelOffsets(sampleIndex, :);
    text(ax, labelPoint(1), labelPoint(2), ...
        sprintf('F(p_%d)', sampleIndex), ...
        'FontName', 'Times New Roman', ...
        'FontSize', 10.0, ...
        'Color', pressureColors(sampleIndex, :));
end

meanVector = displayScale * mappedIncrement;
quiver(ax, origin(1), origin(2), meanVector(1), meanVector(2), 0, ...
    'Color', colors.control, ...
    'LineWidth', 2.45, ...
    'MaxHeadSize', 0.64);
scatter(ax, origin(1), origin(2), 43, colors.path, ...
    'filled', ...
    'MarkerEdgeColor', 'w', ...
    'LineWidth', 0.65);
scatter(ax, origin(1) + meanVector(1), origin(2) + meanVector(2), ...
    38, colors.control, ...
    'filled', ...
    'MarkerEdgeColor', 'w', ...
    'LineWidth', 0.65);
text(ax, 5.05, 1.15, ...
    'Mean direction', ...
    'HorizontalAlignment', 'left', ...
    'FontName', 'Times New Roman', ...
    'FontSize', 10.0, ...
    'Color', colors.control);

exportgraphics(fig, pngPath, ...
    'Resolution', 300, ...
    'BackgroundColor', 'white');
exportgraphics(fig, pdfPath, ...
    'ContentType', 'vector', ...
    'BackgroundColor', 'white');
close(fig);

outputs = struct('pngPath', pngPath, 'pdfPath', pdfPath);
fprintf('CVF mapping figure written to:\n%s\n%s\n', pngPath, pdfPath);
end
