function outputs = make_cvf_ae_main_summary_figure(sourceDir, figureDir)
%MAKE_CVF_AE_MAIN_SUMMARY_FIGURE Plot nonredundant main-comparison summaries.
%
% The function reads the frozen selected-7 result summaries and creates
% feasibility-rate and average-rank figures without rerunning optimization.

projectRoot = fileparts(mfilename('fullpath'));
if nargin < 1 || isempty(sourceDir)
    sourceDir = fullfile(projectRoot, 'routes', 'route_b_cvf_ae', 'results', ...
        'cvf_ae_selected7_paper_artifacts_rerun_20260707_101155');
end
if nargin < 2 || isempty(figureDir)
    figureDir = fullfile(projectRoot, 'routes', 'route_b_cvf_ae', ...
        'paper_ajse_zh', 'figures');
end

summaryPath = fullfile(sourceDir, 'selected7_summary_long.csv');
rankPath = fullfile(sourceDir, 'selected7_average_rank.csv');
assert(isfile(summaryPath), 'Missing selected-7 summary: %s', summaryPath);
assert(isfile(rankPath), 'Missing selected-7 rank summary: %s', rankPath);
assert(isfolder(figureDir), 'Missing paper figure directory: %s', figureDir);

algorithms = ["AE", "PSO", "GWO", "HHO", "ERIME", "MSCSO", "CVF-AE"];
sceneIds = 1:3;
summary = readtable(summaryPath, 'TextType', 'string');
rankSummary = readtable(rankPath, 'TextType', 'string');

feasibility = nan(numel(algorithms), numel(sceneIds));
averageRank = nan(numel(algorithms), 1);
for algorithmIndex = 1:numel(algorithms)
    algorithm = algorithms(algorithmIndex);
    for sceneIndex = 1:numel(sceneIds)
        mask = summary.Algorithm == algorithm & summary.Scene == sceneIds(sceneIndex);
        assert(nnz(mask) == 1, ...
            'Expected one row for %s in Scene %d.', algorithm, sceneIds(sceneIndex));
        feasibility(algorithmIndex, sceneIndex) = summary.Feasibility(mask);
    end
    rankMask = rankSummary.Algorithm == algorithm;
    assert(nnz(rankMask) == 1, 'Expected one average-rank row for %s.', algorithm);
    averageRank(algorithmIndex) = rankSummary.AverageRank(rankMask);
end

colors = localAlgorithmColors(algorithms);
feasibilityBaseName = "selected7_feasibility_rates";
rankBaseName = "selected7_average_rank";
commonAxesPosition = [0.20, 0.19, 0.75, 0.66];

feasibilityFigure = figure( ...
    'Visible', 'off', ...
    'Color', 'w', ...
    'Position', [80, 80, 650, 560]);
feasibilityAxes = axes(feasibilityFigure);
set(feasibilityAxes, 'Position', commonAxesPosition);
hold(feasibilityAxes, 'on');
sceneColors = [
    0.00, 0.45, 0.70
    0.84, 0.37, 0.00
    0.40, 0.25, 0.65];
sceneMarkers = {'o', 's', '^'};
lineHandles = gobjects(numel(sceneIds), 1);
algorithmPositions = 1:numel(algorithms);
sceneOffsets = [-0.10, 0, 0.10];
for sceneIndex = 1:numel(sceneIds)
    lineHandles(sceneIndex) = plot(feasibilityAxes, ...
        algorithmPositions + sceneOffsets(sceneIndex), ...
        feasibility(:, sceneIndex), ...
        'Color', sceneColors(sceneIndex, :), ...
        'LineStyle', 'none', ...
        'LineWidth', 1.2, ...
        'Marker', sceneMarkers{sceneIndex}, ...
        'MarkerSize', 7.0, ...
        'MarkerFaceColor', 'w', ...
        'MarkerEdgeColor', sceneColors(sceneIndex, :));
end
set(feasibilityAxes, ...
    'XTick', algorithmPositions, ...
    'XTickLabel', algorithms, ...
    'YTick', 0:0.2:1, ...
    'FontName', 'Times New Roman', ...
    'FontSize', 10.5, ...
    'LineWidth', 0.9, ...
    'Box', 'on', ...
    'YGrid', 'on', ...
    'XGrid', 'off', ...
    'GridAlpha', 0.16);
xtickangle(feasibilityAxes, 32);
xlim(feasibilityAxes, [0.7, numel(algorithms) + 0.3]);
ylim(feasibilityAxes, [0, 1.05]);
ylabel(feasibilityAxes, 'Feasibility rate');
legend(feasibilityAxes, lineHandles, compose('Scene %d', sceneIds), ...
    'Location', 'northoutside', ...
    'Orientation', 'horizontal', ...
    'NumColumns', 3, ...
    'Box', 'off', ...
    'FontName', 'Times New Roman', ...
    'FontSize', 9.5);
set(feasibilityAxes, 'Position', commonAxesPosition);
localExport(feasibilityFigure, sourceDir, figureDir, feasibilityBaseName);
close(feasibilityFigure);

rankFigure = figure( ...
    'Visible', 'off', ...
    'Color', 'w', ...
    'Position', [80, 80, 650, 560]);
rankAxes = axes(rankFigure);
set(rankAxes, 'Position', commonAxesPosition);
rankBars = barh(rankAxes, 1:numel(algorithms), averageRank, 0.62, ...
    'FaceColor', 'flat', ...
    'EdgeColor', 'none');
rankBars.CData = colors;
hold(rankAxes, 'on');
for algorithmIndex = 1:numel(algorithms)
    fontWeight = 'normal';
    if algorithms(algorithmIndex) == "CVF-AE"
        fontWeight = 'bold';
    end
    text(rankAxes, averageRank(algorithmIndex) + 0.10, algorithmIndex, ...
        sprintf('%.2f', averageRank(algorithmIndex)), ...
        'FontName', 'Times New Roman', ...
        'FontSize', 10, ...
        'FontWeight', fontWeight, ...
        'VerticalAlignment', 'middle');
end
set(rankAxes, ...
    'YTick', 1:numel(algorithms), ...
    'YTickLabel', algorithms, ...
    'YDir', 'reverse', ...
    'XTick', 0:1:7, ...
    'FontName', 'Times New Roman', ...
    'FontSize', 10.5, ...
    'LineWidth', 0.9, ...
    'Box', 'on', ...
    'XGrid', 'on', ...
    'YGrid', 'off', ...
    'GridAlpha', 0.16);
xlim(rankAxes, [0, 7.6]);
ylim(rankAxes, [0.4, numel(algorithms) + 0.6]);
xlabel(rankAxes, 'Average rank');
localExport(rankFigure, sourceDir, figureDir, rankBaseName);
close(rankFigure);

outputs = struct();
outputs.sourceDir = sourceDir;
outputs.feasibilityPng = fullfile(figureDir, feasibilityBaseName + ".png");
outputs.rankPng = fullfile(figureDir, rankBaseName + ".png");
fprintf('Main-comparison summary figures written to:\n%s\n%s\n', ...
    outputs.feasibilityPng, outputs.rankPng);
end

function colors = localAlgorithmColors(algorithms)
palette = containers.Map();
palette('AE') = [0.45, 0.45, 0.45];
palette('PSO') = [0.00, 0.45, 0.70];
palette('GWO') = [0.84, 0.37, 0.00];
palette('HHO') = [0.80, 0.47, 0.65];
palette('ERIME') = [0.35, 0.70, 0.90];
palette('MSCSO') = [0.40, 0.25, 0.65];
palette('CVF-AE') = [0.00, 0.14, 0.32];
colors = zeros(numel(algorithms), 3);
for algorithmIndex = 1:numel(algorithms)
    colors(algorithmIndex, :) = palette(char(algorithms(algorithmIndex)));
end
end

function localExport(fig, sourceDir, figureDir, baseName)
resultPng = fullfile(sourceDir, baseName + ".png");
resultPdf = fullfile(sourceDir, baseName + ".pdf");
paperPng = fullfile(figureDir, baseName + ".png");
exportgraphics(fig, resultPng, 'Resolution', 300, 'BackgroundColor', 'white');
exportgraphics(fig, resultPdf, 'ContentType', 'vector', 'BackgroundColor', 'white');
copyfile(resultPng, paperPng);
end
