function outputs = make_cvf_ae_review_preview_figures(previewDir)
%MAKE_CVF_AE_REVIEW_PREVIEW_FIGURES Create non-paper figure alternatives.
%
% These previews read frozen paper results and are intentionally isolated
% from the manuscript's active figures.

projectRoot = fileparts(mfilename('fullpath'));
if nargin < 1 || isempty(previewDir)
    previewDir = fullfile(projectRoot, 'routes', 'route_b_cvf_ae', ...
        'paper_ajse_zh', 'figures', 'review_previews');
end
if ~exist(previewDir, 'dir')
    mkdir(previewDir);
end

selected7Dir = fullfile(projectRoot, 'routes', 'route_b_cvf_ae', ...
    'results', 'cvf_ae_selected7_paper_artifacts_rerun_20260707_101155');
unifiedDir = fullfile(projectRoot, 'routes', 'route_b_cvf_ae', ...
    'results', 'cvf_ae_selected7_main_comparison_formal_20260707_101155');
ablationDir = fullfile(projectRoot, 'routes', 'route_b_cvf_ae', ...
    'results', 'cvf_ae_paper_results_package_20260624_from_formal_results');

outputs = struct();
outputs.convergence = localConvergencePreview( ...
    unifiedDir, previewDir);
outputs.significance = localSignificancePreview( ...
    selected7Dir, previewDir);
outputs.overhead = localOverheadPreview( ...
    selected7Dir, ablationDir, previewDir);

fprintf('Review-only previews written to:\n%s\n%s\n%s\n', ...
    outputs.convergence, outputs.significance, outputs.overhead);
end

function pngPath = localConvergencePreview(unifiedDir, previewDir)
resultPath = fullfile(unifiedDir, 'uav_comparison_results.mat');
assert(isfile(resultPath), 'Missing convergence MAT file: %s', resultPath);
data = load(resultPath, 'allResults', 'cfg');
algorithms = string(data.cfg.algorithms);
colors = localAlgorithmColors(algorithms);
lineStyles = ["-", "--", "-.", ":", "-", "--", "-"];

fig = figure( ...
    'Visible', 'off', ...
    'Color', 'w', ...
    'Position', [40, 60, 1500, 520]);
layout = tiledlayout(fig, 1, 3, ...
    'TileSpacing', 'compact', ...
    'Padding', 'compact');
legendHandles = gobjects(numel(algorithms), 1);

for sceneIndex = 1:3
    ax = nexttile(layout, sceneIndex);
    hold(ax, 'on');
    curves = cell(numel(algorithms), 1);
    for algorithmIndex = 1:numel(algorithms)
        curves{algorithmIndex} = localMeanCurve( ...
            data.allResults{sceneIndex, algorithmIndex});
        width = 1.25;
        if algorithms(algorithmIndex) == "CVF-AE"
            width = 2.6;
        end
        legendHandles(algorithmIndex) = plot(ax, ...
            1:numel(curves{algorithmIndex}), ...
            curves{algorithmIndex}, ...
            'Color', colors(algorithmIndex, :), ...
            'LineStyle', lineStyles(algorithmIndex), ...
            'LineWidth', width);
    end
    set(ax, ...
        'FontName', 'Times New Roman', ...
        'FontSize', 9.5, ...
        'LineWidth', 0.9, ...
        'Box', 'on', ...
        'XGrid', 'off', ...
        'YGrid', 'on', ...
        'GridAlpha', 0.14);
    xlabel(ax, 'Iteration');
    if sceneIndex == 1
        ylabel(ax, 'Feasible-aware best fitness');
    end
    title(ax, sprintf('Scene %d', sceneIndex), ...
        'FontWeight', 'normal');

    curveLength = max(cellfun(@numel, curves));
    lateStart = max(1, round(0.72 * curveLength));
    inset = axes(fig, 'Position', localInsetPosition(sceneIndex));
    hold(inset, 'on');
    for algorithmIndex = 1:numel(algorithms)
        curve = curves{algorithmIndex};
        x = lateStart:numel(curve);
        plot(inset, x, curve(x), ...
            'Color', colors(algorithmIndex, :), ...
            'LineStyle', lineStyles(algorithmIndex), ...
            'LineWidth', 0.9 + 0.8 * (algorithms(algorithmIndex) == "CVF-AE"));
    end
    set(inset, ...
        'FontName', 'Times New Roman', ...
        'FontSize', 7.2, ...
        'LineWidth', 0.7, ...
        'Box', 'on', ...
        'XGrid', 'off', ...
        'YGrid', 'on', ...
        'GridAlpha', 0.12);
    xlim(inset, [lateStart, curveLength]);
end

legend(ax, legendHandles, cellstr(algorithms), ...
    'Orientation', 'horizontal', ...
    'NumColumns', 7, ...
    'Location', 'southoutside', ...
    'Box', 'off', ...
    'FontName', 'Times New Roman', ...
    'FontSize', 8.8);

pngPath = fullfile(previewDir, 'test_figure5_convergence_with_late_insets.png');
pdfPath = fullfile(previewDir, 'test_figure5_convergence_with_late_insets.pdf');
exportgraphics(fig, pngPath, ...
    'Resolution', 300, ...
    'BackgroundColor', 'white');
exportgraphics(fig, pdfPath, ...
    'ContentType', 'vector', ...
    'BackgroundColor', 'white');
close(fig);
end

function position = localInsetPosition(sceneIndex)
left = [0.205, 0.530, 0.855];
position = [left(sceneIndex), 0.55, 0.105, 0.25];
end

function meanCurve = localMeanCurve(results)
curves = arrayfun(@(result) result.convergence(:), ...
    results, ...
    'UniformOutput', false);
maxLength = max(cellfun(@numel, curves));
matrix = nan(numel(curves), maxLength);
for runIndex = 1:numel(curves)
    curve = curves{runIndex};
    matrix(runIndex, 1:numel(curve)) = curve;
    if numel(curve) < maxLength
        matrix(runIndex, numel(curve) + 1:end) = curve(end);
    end
end
meanCurve = mean(matrix, 1, 'omitnan');
end

function pngPath = localSignificancePreview(selected7Dir, previewDir)
sourcePath = fullfile(selected7Dir, ...
    'selected7_pairwise_rank_sum_holm.csv');
assert(isfile(sourcePath), 'Missing significance table: %s', sourcePath);
pairwise = readtable(sourcePath, 'TextType', 'string');
baselines = ["AE", "PSO", "GWO", "HHO", "ERIME", "MSCSO"];
sceneIds = 1:3;
effect = nan(numel(sceneIds), numel(baselines));
relation = strings(size(effect));
for sceneIndex = 1:numel(sceneIds)
    for baselineIndex = 1:numel(baselines)
        mask = pairwise.Scene == sceneIds(sceneIndex) & ...
            pairwise.Baseline == baselines(baselineIndex);
        assert(nnz(mask) == 1, ...
            'Expected one significance row for Scene %d, %s.', ...
            sceneIds(sceneIndex), baselines(baselineIndex));
        effect(sceneIndex, baselineIndex) = ...
            pairwise.CliffsDeltaLowerBetter(mask);
        relation(sceneIndex, baselineIndex) = ...
            pairwise.SceneHolmResult(mask);
    end
end

fig = figure( ...
    'Visible', 'off', ...
    'Color', 'w', ...
    'Position', [80, 80, 1060, 470]);
ax = axes(fig, 'Position', [0.10, 0.17, 0.77, 0.72]);
imagesc(ax, 1:numel(baselines), sceneIds, effect);
colormap(ax, localDivergingPalette(121));
clim(ax, [-1, 1]);
set(ax, ...
    'XTick', 1:numel(baselines), ...
    'XTickLabel', baselines, ...
    'YTick', sceneIds, ...
    'YTickLabel', compose('Scene %d', sceneIds), ...
    'FontName', 'Times New Roman', ...
    'FontSize', 11, ...
    'LineWidth', 0.9, ...
    'TickLength', [0, 0], ...
    'Box', 'on');
xlabel(ax, 'Baseline');
ylabel(ax, 'Test scene');

for sceneIndex = 1:numel(sceneIds)
    for baselineIndex = 1:numel(baselines)
        textColor = [0.12, 0.12, 0.12];
        if abs(effect(sceneIndex, baselineIndex)) > 0.62
            textColor = [1, 1, 1];
        end
        text(ax, baselineIndex, sceneIndex, ...
            sprintf('%+.2f  %s', ...
            effect(sceneIndex, baselineIndex), ...
            relation(sceneIndex, baselineIndex)), ...
            'HorizontalAlignment', 'center', ...
            'VerticalAlignment', 'middle', ...
            'FontName', 'Times New Roman', ...
            'FontSize', 10, ...
            'FontWeight', 'bold', ...
            'Color', textColor);
    end
end

colorBar = colorbar(ax, 'eastoutside');
colorBar.Position = [0.90, 0.17, 0.025, 0.72];
colorBar.Label.String = 'Cliff''s delta (positive favors CVF-AE)';
colorBar.Label.FontName = 'Times New Roman';
colorBar.FontName = 'Times New Roman';

pngPath = fullfile(previewDir, 'test_table5_effect_size_heatmap.png');
pdfPath = fullfile(previewDir, 'test_table5_effect_size_heatmap.pdf');
exportgraphics(fig, pngPath, ...
    'Resolution', 300, ...
    'BackgroundColor', 'white');
exportgraphics(fig, pdfPath, ...
    'ContentType', 'vector', ...
    'BackgroundColor', 'white');
close(fig);
end

function pngPath = localOverheadPreview(selected7Dir, ablationDir, previewDir)
mainPath = fullfile(selected7Dir, 'selected7_runs.csv');
ablationPath = fullfile(ablationDir, 'paper_table_ablation.csv');
assert(isfile(mainPath), 'Missing selected-7 runs: %s', mainPath);
assert(isfile(ablationPath), 'Missing ablation table: %s', ablationPath);
mainRuns = readtable(mainPath, 'TextType', 'string');
ablation = readtable(ablationPath, 'TextType', 'string');
sceneIds = 1:3;

mainTrigger = nan(size(sceneIds));
mainSuccess = nan(size(sceneIds));
ablationTrigger = nan(size(sceneIds));
ablationSuccess = nan(size(sceneIds));
evaluationRatio = nan(size(sceneIds));
for sceneIndex = 1:numel(sceneIds)
    mainMask = mainRuns.PaperScene == sceneIds(sceneIndex) & ...
        mainRuns.Algorithm == "CVF-AE";
    mainTrigger(sceneIndex) = mean( ...
        mainRuns.ViabilityFieldCount(mainMask), 'omitnan');
    mainSuccess(sceneIndex) = mean( ...
        mainRuns.ViabilityFieldSuccessCount(mainMask), 'omitnan');

    fullMask = ablation.Scene == sceneIds(sceneIndex) & ...
        ablation.Variant == "CVF-AE";
    withoutMask = ablation.Scene == sceneIds(sceneIndex) & ...
        ablation.Variant == "CVF-AE-w/o-CVF";
    ablationTrigger(sceneIndex) = ablation.CVFTriggerCount(fullMask);
    ablationSuccess(sceneIndex) = ablation.CVFSuccessCount(fullMask);
    evaluationRatio(sceneIndex) = ...
        ablation.NEvals(fullMask) / ablation.NEvals(withoutMask);
end

fig = figure( ...
    'Visible', 'off', ...
    'Color', 'w', ...
    'Position', [80, 80, 1120, 470]);
layout = tiledlayout(fig, 1, 2, ...
    'TileSpacing', 'compact', ...
    'Padding', 'compact');

ax1 = nexttile(layout, 1);
groupValues = [
    mainTrigger(1), mainSuccess(1)
    ablationTrigger(1), ablationSuccess(1)
    mainTrigger(2), mainSuccess(2)
    ablationTrigger(2), ablationSuccess(2)
    mainTrigger(3), mainSuccess(3)
    ablationTrigger(3), ablationSuccess(3)];
bars = bar(ax1, groupValues, 'grouped');
bars(1).FaceColor = [0.00, 0.14, 0.32];
bars(2).FaceColor = [0.35, 0.70, 0.90];
bars(1).EdgeColor = 'none';
bars(2).EdgeColor = 'none';
set(ax1, ...
    'XTick', 1:6, ...
    'XTickLabel', {'S1 Main', 'S1 Abl.', 'S2 Main', ...
    'S2 Abl.', 'S3 Main', 'S3 Abl.'}, ...
    'FontName', 'Times New Roman', ...
    'FontSize', 9.5, ...
    'LineWidth', 0.9, ...
    'Box', 'on', ...
    'YGrid', 'on', ...
    'XGrid', 'off', ...
    'GridAlpha', 0.15);
xtickangle(ax1, 30);
ylabel(ax1, 'Mean candidate count');
legend(ax1, {'Triggered', 'Accepted'}, ...
    'Location', 'northwest', ...
    'Box', 'off');

ax2 = nexttile(layout, 2);
plot(ax2, sceneIds, evaluationRatio, ...
    'LineStyle', 'none', ...
    'Marker', 'd', ...
    'MarkerSize', 8, ...
    'MarkerFaceColor', [0.84, 0.37, 0.00], ...
    'MarkerEdgeColor', [0.62, 0.27, 0.00], ...
    'LineWidth', 1.1);
hold(ax2, 'on');
yline(ax2, 1, '--', ...
    'Color', [0.48, 0.48, 0.48], ...
    'LineWidth', 1.0);
for sceneIndex = 1:numel(sceneIds)
    text(ax2, sceneIds(sceneIndex), evaluationRatio(sceneIndex) + 0.0008, ...
        sprintf('%.3f', evaluationRatio(sceneIndex)), ...
        'HorizontalAlignment', 'center', ...
        'FontName', 'Times New Roman', ...
        'FontSize', 10);
end
set(ax2, ...
    'XTick', sceneIds, ...
    'XTickLabel', compose('Scene %d', sceneIds), ...
    'FontName', 'Times New Roman', ...
    'FontSize', 10, ...
    'LineWidth', 0.9, ...
    'Box', 'on', ...
    'YGrid', 'on', ...
    'XGrid', 'off', ...
    'GridAlpha', 0.15);
xlim(ax2, [0.65, 3.35]);
ylim(ax2, [0.998, 1.016]);
ylabel(ax2, 'nEvals ratio vs. w/o-CVF');

pngPath = fullfile(previewDir, 'test_table6_sparse_overhead_summary.png');
pdfPath = fullfile(previewDir, 'test_table6_sparse_overhead_summary.pdf');
exportgraphics(fig, pngPath, ...
    'Resolution', 300, ...
    'BackgroundColor', 'white');
exportgraphics(fig, pdfPath, ...
    'ContentType', 'vector', ...
    'BackgroundColor', 'white');
close(fig);
end

function colors = localAlgorithmColors(algorithms)
palette = containers.Map();
palette('AE') = [0.45, 0.45, 0.45];
palette('PSO') = [0.00, 0.45, 0.70];
palette('GWO') = [0.84, 0.37, 0.00];
palette('HHO') = [0.80, 0.47, 0.65];
palette('ERIME') = [0.35, 0.70, 0.90];
palette('MSCSO') = [0.40, 0.25, 0.65];
palette('CVF-AE') = [0.00, 0.14, 0.32];
colors = zeros(numel(algorithms), 3);
for algorithmIndex = 1:numel(algorithms)
    colors(algorithmIndex, :) = palette(char(algorithms(algorithmIndex)));
end
end

function colors = localDivergingPalette(colorCount)
anchors = [
    0.84, 0.37, 0.00
    0.94, 0.72, 0.54
    0.94, 0.94, 0.93
    0.50, 0.72, 0.82
    0.00, 0.14, 0.32];
anchorX = linspace(0, 1, size(anchors, 1));
queryX = linspace(0, 1, colorCount);
colors = interp1(anchorX, anchors, queryX, 'pchip');
colors = min(max(colors, 0), 1);
end
