function outputs = redraw_selected7_boxplot_figure(sourceDir, figureDir)
%REDRAW_SELECTED7_BOXPLOT_FIGURE Redraw frozen selected-7 boxplots.
%
% Diamonds mark arithmetic means. No optimization is executed.

projectRoot = fileparts(mfilename('fullpath'));
if nargin < 1 || isempty(sourceDir)
    sourceDir = fullfile(projectRoot, 'routes', 'route_b_cvf_ae', 'results', ...
        'cvf_ae_selected7_paper_artifacts_rerun_20260707_101155');
end
if nargin < 2 || isempty(figureDir)
    figureDir = fullfile(projectRoot, 'routes', 'route_b_cvf_ae', ...
        'paper_ajse_zh', 'figures');
end

runsPath = fullfile(sourceDir, 'selected7_runs.csv');
assert(isfile(runsPath), 'Missing selected-7 runs: %s', runsPath);
assert(isfolder(figureDir), 'Missing paper figure directory: %s', figureDir);

runs = readtable(runsPath, 'TextType', 'string');
algorithms = ["AE", "PSO", "GWO", "HHO", "ERIME", "MSCSO", "CVF-AE"];
sceneIds = 1:3;
colors = localAlgorithmColors(algorithms);

fig = figure( ...
    'Visible', 'off', ...
    'Color', 'w', ...
    'Position', [40, 60, 1460, 460]);
layout = tiledlayout(fig, 1, 3, ...
    'TileSpacing', 'compact', ...
    'Padding', 'compact');

for sceneIndex = 1:numel(sceneIds)
    ax = nexttile(layout, sceneIndex);
    hold(ax, 'on');
    for algorithmIndex = 1:numel(algorithms)
        mask = runs.PaperScene == sceneIds(sceneIndex) & ...
            runs.Algorithm == algorithms(algorithmIndex);
        values = runs.BestFitness(mask);
        assert(numel(values) == 30, ...
            'Expected 30 runs for Scene %d, %s.', ...
            sceneIds(sceneIndex), algorithms(algorithmIndex));
        chart = boxchart(ax, ...
            algorithmIndex * ones(size(values)), ...
            values, ...
            'MarkerStyle', '.', ...
            'JitterOutliers', 'on', ...
            'BoxWidth', 0.58);
        chart.BoxFaceColor = colors(algorithmIndex, :);
        chart.BoxFaceAlpha = 0.55;
        chart.WhiskerLineColor = colors(algorithmIndex, :) * 0.65;
        chart.MarkerColor = colors(algorithmIndex, :) * 0.65;
        if algorithms(algorithmIndex) == "CVF-AE"
            chart.LineWidth = 1.35;
        end
        plot(ax, algorithmIndex, mean(values, 'omitnan'), 'd', ...
            'LineStyle', 'none', ...
            'MarkerSize', 6.0, ...
            'MarkerFaceColor', 'w', ...
            'MarkerEdgeColor', colors(algorithmIndex, :) * 0.55, ...
            'LineWidth', 1.15);
    end
    set(ax, ...
        'XTick', 1:numel(algorithms), ...
        'XTickLabel', algorithms, ...
        'FontName', 'Times New Roman', ...
        'FontSize', 9.5, ...
        'LineWidth', 0.9, ...
        'Box', 'on', ...
        'YGrid', 'on', ...
        'XGrid', 'off', ...
        'GridAlpha', 0.16);
    xtickangle(ax, 35);
    xlim(ax, [0.5, numel(algorithms) + 0.5]);
    title(ax, sprintf('Scene %d', sceneIds(sceneIndex)), ...
        'FontWeight', 'normal');
    if sceneIndex == 1
        ylabel(ax, 'Best fitness');
    end
end

baseName = "selected7_boxplots";
sourcePng = fullfile(sourceDir, baseName + ".png");
sourcePdf = fullfile(sourceDir, baseName + ".pdf");
paperPng = fullfile(figureDir, baseName + ".png");
exportgraphics(fig, sourcePng, ...
    'Resolution', 300, ...
    'BackgroundColor', 'white');
exportgraphics(fig, sourcePdf, ...
    'ContentType', 'vector', ...
    'BackgroundColor', 'white');
copyfile(sourcePng, paperPng);
close(fig);

outputs = struct( ...
    'sourcePng', sourcePng, ...
    'sourcePdf', sourcePdf, ...
    'paperPng', paperPng);
fprintf('Selected-7 boxplot figure written to:\n%s\n', paperPng);
end

function colors = localAlgorithmColors(algorithms)
palette = containers.Map();
palette('AE') = [0.45, 0.45, 0.45];
palette('PSO') = [0.00, 0.45, 0.70];
palette('GWO') = [0.84, 0.37, 0.00];
palette('HHO') = [0.80, 0.47, 0.65];
palette('ERIME') = [0.35, 0.70, 0.90];
palette('MSCSO') = [0.40, 0.25, 0.65];
palette('CVF-AE') = [0.00, 0.14, 0.32];
colors = zeros(numel(algorithms), 3);
for algorithmIndex = 1:numel(algorithms)
    colors(algorithmIndex, :) = palette(char(algorithms(algorithmIndex)));
end
end
