function summary = run_cvf_ae_formal_ablation(cfg)
%RUN_CVF_AE_FORMAL_ABLATION Formal Route B CVF-AE ablation runner.
%
% This wrapper freezes the Sparse 2.0 configuration and delegates execution to
% run_cvf_ae_gate_diagnostics, which already supports per-run records,
% resumeExisting, aggregate CSV output, and CVF metrics.

if nargin < 1 || isempty(cfg)
    cfg = struct();
end

cfg = localApplyFormalDefaults(cfg);
summary = run_cvf_ae_gate_diagnostics(cfg);

formalNote = fullfile(cfg.resultDir, 'CVF_AE_FORMAL_ABLATION_README.md');
localWriteFormalReadme(formalNote, cfg, summary);

fprintf('\nFormal CVF-AE ablation wrapper complete:\n');
fprintf('  %s\n', cfg.resultDir);
fprintf('  %s\n', formalNote);
end

function cfg = localApplyFormalDefaults(cfg)
cfg.gateLabel = 'Formal Ablation';
cfg.decisionMode = 'medium';

if ~isfield(cfg, 'sceneIds') || isempty(cfg.sceneIds)
    cfg.sceneIds = [1, 2, 4];
end
if ~isfield(cfg, 'algorithms') || isempty(cfg.algorithms)
    cfg.algorithms = {'Base-AE', ...
        'CVF-AE-w/o-Init', ...
        'CVF-AE-w/o-StateAdaptiveCVF', ...
        'CVF-AE-w/o-SparsePreservation', ...
        'CVF-AE-w/o-CVF', ...
        'CVF-AE'};
end
if ~isfield(cfg, 'nRuns') || isempty(cfg.nRuns)
    cfg.nRuns = 30;
end
if ~isfield(cfg, 'baseSeed') || isempty(cfg.baseSeed)
    cfg.baseSeed = 20260623;
end
if ~isfield(cfg, 'paramsOverride') || ~isstruct(cfg.paramsOverride)
    cfg.paramsOverride = struct();
end
if ~isfield(cfg.paramsOverride, 'popSize')
    cfg.paramsOverride.popSize = 30;
end
if ~isfield(cfg.paramsOverride, 'maxIter')
    cfg.paramsOverride.maxIter = 300;
end
if ~isfield(cfg, 'resumeExisting')
    cfg.resumeExisting = false;
end
if ~isfield(cfg, 'resultDir') || isempty(cfg.resultDir)
    cfg.resultDir = fullfile(pwd, 'routes', 'route_b_cvf_ae', 'results', ...
        ['cvf_ae_formal_ablation_' datestr(now, 'yyyymmdd_HHMMSS')]);
end
end

function localWriteFormalReadme(filePath, cfg, summary)
fid = fopen(filePath, 'w');
if fid < 0
    warning('Could not write formal ablation README: %s', filePath);
    return;
end
c = onCleanup(@() fclose(fid));

fprintf(fid, '# CVF-AE Formal Ablation Run\n\n');
fprintf(fid, 'This folder was generated by `run_cvf_ae_formal_ablation.m`.\n\n');
fprintf(fid, '## Frozen Configuration\n\n');
fprintf(fid, '- Default version: `CVF-AE Sparse 2.0`\n');
fprintf(fid, '- Freeze document: `routes/route_b_cvf_ae/docs/CVF_AE_SPARSE2_DEFAULTS.md`\n');
fprintf(fid, '- Scenes: `%s`\n', mat2str(cfg.sceneIds));
fprintf(fid, '- Algorithms: `%s`\n', strjoin(cfg.algorithms, ', '));
fprintf(fid, '- nRuns: `%d`\n', cfg.nRuns);
fprintf(fid, '- popSize: `%d`\n', cfg.paramsOverride.popSize);
fprintf(fid, '- maxIter: `%d`\n', cfg.paramsOverride.maxIter);
fprintf(fid, '- baseSeed: `%d`\n', cfg.baseSeed);
fprintf(fid, '- resumeExisting: `%d`\n\n', logical(cfg.resumeExisting));

fprintf(fid, '## Output Files\n\n');
fprintf(fid, '- `run_records/`: per-run MAT records, ignored by Git.\n');
fprintf(fid, '- `cvf_ae_gate_runs.csv`: per-run table.\n');
fprintf(fid, '- `cvf_ae_gate_summary.csv`: aggregate table.\n');
fprintf(fid, '- `cvf_ae_gate_average_rank.csv`: rank summary.\n');
fprintf(fid, '- `cvf_ae_gate_summary_workspace.mat`: summary workspace.\n');
fprintf(fid, '- `CVF_AE_GATE_DECISION.md`: automatic decision summary.\n\n');

if isfield(summary, 'decision')
    fprintf(fid, '## Automatic Decision\n\n');
    fprintf(fid, '- `%s`\n', summary.decision.label);
    fprintf(fid, '- %s\n', summary.decision.reason);
end
end
